FROM node:18-alpine

WORKDIR /app

# Copia arquivos de dependências
COPY package*.json ./
RUN npm install

# Copia o código da aplicação
COPY . .

# Expõe a porta
EXPOSE 3000

# Comando para iniciar
CMD ["node", "server.js"]